Page settings
whityha/calculator pull request #10
Opened 2023-02-14 11:14 UTC by whityha

1. Сделал страничку Settings.
2. Перенёс туда функционал изменения темы.
3. Добавил кнопку скрытия/открытия History.
4. Добавил кнопку очистки истории в настройках как на макете.
5. **Deploy**: https://brilliant-toffee-62d5cf.netlify.app/
6. 
![image](https://user-images.githubusercontent.com/51292270/218719664-b32bc965-e3bf-4669-8d28-acb5761940ab.png)

2023-02-14 13:28 UTC, anyaprystavka requested changes

2023-02-14 13:28 UTC, anyaprystavka commented on src/pages/config.js
> +    LINKS_CC: [
вот тут странно выглядит, постоянно меняется массив, предлагаю сделать так, чтобы просто переключаться между страницами, оставив и FC И  CC  в Header
и тем самым убрать страницу по дефолту, что может быть удобнее

2023-02-14 13:28 UTC, anyaprystavka commented on src/store/initialState.jsx
> +    theme: 'light',
если так удобно выносить его, то ок, ты наверное где-то видел это
но можно просто его оставить в файле редьюсера
а если большой стор, то разбить на редьюсеры

2023-02-14 13:28 UTC, anyaprystavka commented on src/styled/theme/theme.js
>      colored: {
при переключении на тему colored, цвет остается темным и названия не очень читабельны

2023-02-14 13:30 UTC, whityha commented on src/components/History/HistoryCC.jsx
> +            display: { formulas },
Исправлено в другой ветке.

2023-02-14 13:31 UTC, whityha commented on src/components/History/HistoryFC.jsx
>      const formulas = useSelector(({ display: { formulas: forms } }) => forms);
Мы уже говорили об этом, всё исправлено в другой ветке.

2023-02-14 13:33 UTC, whityha commented on src/components/SettingsList/SwitcherTheme/styled.js
> +import styled, { css } from 'styled-components';
Чтобы соблюсти DRY. Чтобы не для каждого свойства писать ${(theme: { prop })=> prop}, а сразу вместе, один раз тему достал из пропсов и всё по ней раскидал

2023-02-14 13:40 UTC, whityha commented on src/components/App.jsx
>              <Suspense fallback={<BeatLoader />}>
убрал мигание цвета. Лоадер появляется в верхнем левом углу экрана.

2023-02-14 13:42 UTC, whityha commented on src/store/initialState.jsx
> +    theme: 'light',
Окей. Но пусть пока полежит тут)

2023-02-14 13:48 UTC, whityha commented on src/styled/theme/theme.js
>      colored: {
Сделал

2023-02-14 14:05 UTC, whityha commented on src/pages/config.js
> +    LINKS_CC: [
Удалил StartPage, оставил только 3 ссылки.

2023-02-14 14:14 UTC, whityha commented on src/components/SettingsList/SwitcherTheme/Switcher.jsx
> +                <Option value={DARK}>DARK</Option>
сделал

2023-02-14 14:21 UTC, whityha commented on src/components/Header/Header/HeaderCC.jsx
Сделал

2023-02-14 14:21 UTC, whityha commented on src/components/Header/Header/HeaderFC.jsx
>  import Switcher from '../Switcher/SwitcherFC';
Удалил вообще этот компонент

2023-02-14 14:34 UTC, anyaprystavka requested changes

2023-02-14 14:34 UTC, anyaprystavka commented on src/components/App.jsx
>              <Suspense fallback={<BeatLoader />}>
ты когда-нибудь видел, чтобы лоадер был слева вверху экрана?

2023-02-14 14:34 UTC, anyaprystavka commented on src/styled/theme/theme.js
>      colored: {
нужен деплой, чтобы глянуть

2023-02-14 15:21 UTC, whityha commented on src/components/App.jsx
>              <Suspense fallback={<BeatLoader />}>
Спешу

2023-02-16 07:22 UTC, anyaprystavka requested changes

2023-02-16 07:22 UTC, anyaprystavka commented on src/components/Loader/index.jsx
> +    <WrapperLoader>
просто Wrapper

2023-02-16 07:34 UTC, whityha commented on src/components/config.jsx
> +    { path: DEFAULT, element: <HomeFC /> },
При деплое на netflity нужна начальная страница, чтобы пройти на все другие. Так как я удалил начальную страницу, начальной сделал HomeFC, чтобы всё работало на netflity

2023-02-16 07:35 UTC, whityha commented on src/pages/Settings/styled.js
> +    height: ${({ theme: { heightPercent } }) => heightPercent['100']};
ok

2023-02-16 07:35 UTC, whityha commented on src/components/Loader/index.jsx
> +    <WrapperLoader>
ok

2023-02-16 07:37 UTC, whityha commented on src/components/SettingsList/index.jsx
> +    <WrapperSettingsListFC>
ok

2023-02-16 07:42 UTC, whityha commented on src/store/actions/controlsActions.jsx
> +export const togglerShowHistory = (payload) => ({
Экшен-переключатель, который включает / выключает показ истории операций.

2023-02-16 09:16 UTC, anyaprystavka commented on src/components/config.jsx
> +    { path: DEFAULT, element: <HomeFC /> },
окей, добавь страницу notfound

2023-02-16 09:16 UTC, anyaprystavka commented on src/store/actions/controlsActions.jsx
> +export const togglerShowHistory = (payload) => ({
![image](https://user-images.githubusercontent.com/119484939/219321418-1e25ad05-36ad-4885-9ca3-ab2989d1593d.png)

2023-02-16 09:26 UTC, whityha commented on src/components/config.jsx
> +    { path: DEFAULT, element: <HomeFC /> },
Чтобы это работало, на странице notFound должны быть кнопки для перехода на мои страницы, как это было изначально. По прямой ссылке app/class не будет работать. Не нужно было тогда убирать страницу Start Page.

2023-02-16 09:27 UTC, whityha commented on src/store/actions/controlsActions.jsx
> +export const togglerShowHistory = (payload) => ({
Я переименовал как toggle

2023-02-16 09:35 UTC, anyaprystavka commented on src/components/config.jsx
> +    { path: DEFAULT, element: <HomeFC /> },
пусть она появляется, если пользователь захотел ввести путь в адресной строке и он оказался неправильный

2023-02-16 10:31 UTC, merged