refactor: add algorithm for calculator
whityha/calculator pull request #8
Opened 2023-02-11 22:17 UTC by whityha

1. Добавил рабочий алгоритм на двух стэках в калькулятор.
2. controller из компонента Calculator не могу вынести, так как использую useDispatch внутри контроллера.
3. На проверку работоспособность калькулятора + что заметишь по данному куску кода.
4. ссылка на **DEPLOY** для проверки работоспособности https://brilliant-toffee-62d5cf.netlify.app/function

2023-02-12 07:05 UTC, anyaprystavka requested changes

2023-02-12 08:55 UTC, whityha commented on src/store/actions/displayActions.jsx
>      CLEAR_ALL,
Сделал.

2023-02-12 09:03 UTC, whityha commented on src/store/actions/type.js
> +export const DRAW_HISTORY = 'DISPLAY/DRAW_HISTORY';
в видосе чел какойто объяснял, что это на случай, когда много типов экшенов и чтобы не путаться так делают. Но ок, я уберу.

2023-02-12 09:04 UTC, whityha commented on src/store/reducers/displayReducer.jsx
>      switch (action.type) {
сделал

2023-02-12 09:09 UTC, whityha commented on src/store/reducers/displayReducer.jsx
> +                formulas: [...state.formulas, action.payload],
Изменил название на historyList

2023-02-12 09:19 UTC, whityha commented on src/command/AddCommand.js
> +        this.dig = '+';
No. Поменял.

2023-02-12 09:40 UTC, whityha commented on src/components/Calculator/CalculatorFC.jsx
> +        if (DRAW_HISTORY_BUTTONS.includes(name)) {
сделал

2023-02-15 12:51 UTC, whityha commented on src/command/command.js
> +            const checkItem = () => {
сделал

2023-02-15 13:43 UTC, anyaprystavka requested changes

2023-02-15 13:43 UTC, anyaprystavka commented on src/command/AddCommand.js
> +        this.name = 'plus';
name что?

2023-02-15 13:43 UTC, anyaprystavka commented on src/command/DivideCommand.js
> +        this.name = 'divide';
name что?

2023-02-15 13:43 UTC, anyaprystavka commented on src/command/MultiplyCommand.js
> +        this.name = 'multiply';
name что?

2023-02-15 13:43 UTC, anyaprystavka commented on src/command/ReminderCommand.js
> +        this.name = 'remainder';
name что?

2023-02-15 13:43 UTC, anyaprystavka commented on src/command/SubtractCommand.js
> +        this.name = 'minus';
name что?

2023-02-15 13:43 UTC, anyaprystavka commented on src/command/command.js
> +        this.current = '';
current что? тут что-то с рефами связано?

2023-02-15 13:43 UTC, anyaprystavka commented on src/command/command.js
> +        this.formula = [];
формула? с какими формулами ты работаешь тут?
expression??????

2023-02-15 13:43 UTC, anyaprystavka commented on src/command/command.js
>          this.isRegistered = false;
с какой регистрацией мы работаем?

2023-02-15 13:43 UTC, anyaprystavka commented on src/command/command.js
> +        this.canEqual = true;
может равный?? может просто тогда equal просто тут тогда?

2023-02-15 13:43 UTC, anyaprystavka commented on src/command/command.js
> +        this.addItemInFormula(command);
добавить элемент в формулу? Что такое формула?

2023-02-15 13:43 UTC, anyaprystavka commented on src/command/command.js
> +        this.clearCurrent();
очистить текущий что?

2023-02-15 13:43 UTC, anyaprystavka commented on src/command/command.js
> +    equal(callback = false) {
callback - ладно, может поконкретнее описать что приходит тут?

2023-02-15 13:43 UTC, anyaprystavka commented on src/command/command.js
> +        this.wasEqual = false;
был равен кто? что? не понимаю

2023-02-15 13:43 UTC, anyaprystavka commented on src/command/command.js
> +        this.clear();
очистить что?

2023-02-15 13:43 UTC, anyaprystavka commented on src/command/command.js
> +    openBracket() {
открыта скобка?

2023-02-15 13:43 UTC, anyaprystavka commented on src/command/helpers/changeSignCurrent.js
> +const restoreDotItem = (item) => {
восстановить элемент точку??

2023-02-15 13:43 UTC, anyaprystavka commented on src/command/helpers/result.js
> +    const lastOperatorPriority = () => {
логичнее priorityLastElement - приоритет последнего элемента

2023-02-15 13:43 UTC, anyaprystavka commented on src/command/helpers/result.js
> +    formula.forEach((item) => {
вообще не понимаю что за формула

2023-02-15 13:43 UTC, anyaprystavka commented on src/command/helpers/updateHistoryAndFormula.js
> +const changeDigitCurrent = (digit, current = '') => {
changeCurrentDigit

2023-02-15 13:43 UTC, anyaprystavka commented on src/command/helpers/updateHistoryAndFormula.js
> +    switch (digit) {
вместо digit лучше просто value

2023-02-15 13:43 UTC, anyaprystavka commented on src/command/helpers/updateHistoryAndFormula.js
> +            if (!hasDot) {
containsDot

2023-02-15 13:43 UTC, anyaprystavka commented on src/command/helpers/updateHistoryAndFormula.js
> +export default (digit, formula, history) => {
вообще не понимаю что за формула

2023-02-15 13:43 UTC, anyaprystavka commented on src/store/reducers/control.jsx
> +const controlReducer = (state = initialState, { type } = {}) => {
зачем тут пустой объект?

2023-02-15 13:43 UTC, anyaprystavka commented on src/store/reducers/display.jsx
> +const displayReducer = (state = initialState, { type, payload } = {}) => {
зачем тут пустой объект?

2023-02-15 13:43 UTC, anyaprystavka commented on src/utils/controller.js
> +    if (name === 'bl') {
что за bl, мне нужно гадать

2023-02-15 13:43 UTC, anyaprystavka commented on src/utils/controller.js
> +    if (name === 'br') {
что за br, нужно гадать

2023-02-15 14:11 UTC, whityha commented on src/command/DivideCommand.js
> +        this.name = 'divide';
удалил

2023-02-15 14:11 UTC, whityha commented on src/command/MultiplyCommand.js
> +        this.name = 'multiply';
удалил

2023-02-15 14:11 UTC, whityha commented on src/command/ReminderCommand.js
> +        this.name = 'remainder';
удалил

2023-02-15 14:11 UTC, whityha commented on src/command/SubtractCommand.js
> +        this.name = 'minus';
удалил

2023-02-15 14:13 UTC, whityha commented on src/command/command.js
> +        this.formula = [];
исправил.

2023-02-15 14:20 UTC, whityha commented on src/command/command.js
> +    equal(callback = false) {
изменил.

2023-02-15 14:22 UTC, whityha commented on src/command/command.js
> +        this.clear();
Исправил

2023-02-15 14:25 UTC, whityha commented on src/command/command.js
> +    openBracket() {
Открыть скобку (OpenBracket) 
Закрыть скобку (CloseBracker) 
Методы, который вызываются при нажатии на ( ) в калькуляторе.

2023-02-15 14:29 UTC, whityha commented on src/command/helpers/changeSignCurrent.js
> +const restoreDotItem = (item) => {
изменил

2023-02-15 14:29 UTC, whityha commented on src/command/helpers/result.js
> +    const lastOperatorPriority = () => {
изменил

2023-02-15 14:30 UTC, whityha commented on src/command/helpers/result.js
> +    formula.forEach((item) => {
убрал везде

2023-02-15 14:30 UTC, whityha commented on src/command/helpers/updateHistoryAndFormula.js
> +const changeDigitCurrent = (digit, current = '') => {
исправил

2023-02-15 14:31 UTC, whityha commented on src/command/helpers/updateHistoryAndFormula.js
> +            if (!hasDot) {
ок

2023-02-15 14:32 UTC, whityha commented on src/command/helpers/updateHistoryAndFormula.js
> +    switch (digit) {
Окей, сделал.

2023-02-15 14:32 UTC, whityha commented on src/command/helpers/updateHistoryAndFormula.js
> +export default (digit, formula, history) => {
убрал везде

2023-02-15 14:35 UTC, whityha commented on src/store/reducers/control.jsx
> +const controlReducer = (state = initialState, { type } = {}) => {
убрал

2023-02-15 14:37 UTC, whityha commented on src/store/reducers/display.jsx
> +const displayReducer = (state = initialState, { type, payload } = {}) => {
убрал. Обходил так правильно default params в еслинте. Убрал правило.

2023-02-15 14:41 UTC, whityha commented on src/utils/controller.js
> +    if (name === 'bl') {
исправил

2023-02-15 14:41 UTC, whityha commented on src/utils/controller.js
> +    if (name === 'br') {
исправил

2023-02-15 14:54 UTC, whityha commented on src/command/command.js
>          this.isRegistered = false;
переименовал

2023-02-15 15:05 UTC, whityha commented on src/command/command.js
> +        this.clearCurrent();
изменил

2023-02-15 15:13 UTC, whityha commented on src/command/command.js
> +        this.canEqual = true;
Поменял на более осмысленное

2023-02-15 15:13 UTC, whityha commented on src/command/command.js
> +        this.wasEqual = false;
Поменял

2023-02-16 07:20 UTC, anyaprystavka requested changes

2023-02-16 07:20 UTC, anyaprystavka commented on src/command/helpers/changeSignCurrent.js
> +const preparationItem = (item) => {
за что отвечает эта функция?

2023-02-16 07:20 UTC, anyaprystavka commented on src/command/helpers/result.js
> +export default (expression) => {
назови файл хотя бы результат выражения или подсчеты выражения

2023-02-16 07:20 UTC, anyaprystavka commented on src/command/helpers/result.js
> +            switch (typeof item) {
зачем нужен этот switch?

2023-02-16 07:20 UTC, anyaprystavka commented on src/command/helpers/updateHistoryAndExpression.js
> +        if (string === '-.') return 0;
что значит это условие?

2023-02-16 07:20 UTC, anyaprystavka commented on src/command/helpers/updateHistoryAndExpression.js
> +        expression.push(checkBeforePushInExpression(item));
за что отвечает checkBeforePushInExpression?

2023-02-16 07:20 UTC, anyaprystavka commented on src/command/AddCommand.js
>          const fixed = res !== Infinity ? res.toFixed(3) : Infinity;
Что хранится в fixed?

2023-02-16 07:20 UTC, anyaprystavka commented on src/command/command.js
> +    getResult() {
мне нужно объяснение каждого метода, который написал в CalculatorCommand

2023-02-16 07:46 UTC, whityha commented on src/command/helpers/changeSignCurrent.js
> +const preparationItem = (item) => {
Изменяет знак в числе на противоположенный.

2023-02-16 07:47 UTC, whityha commented on src/command/helpers/result.js
> +export default (expression) => {
заменил на resultExpression

2023-02-16 07:50 UTC, whityha commented on src/command/helpers/updateHistoryAndExpression.js
> +        if (string === '-.') return 0;
Если ты в калькуляторе введешь . или -. (так как в ТЗ есть условие, чтобы мы можем вводить числа как 0.2 и как .2), то эта запись . или -. поменяется на 0 и отправится в expression

2023-02-16 07:51 UTC, whityha commented on src/command/helpers/updateHistoryAndExpression.js
> +        expression.push(checkBeforePushInExpression(item));
Выше описал.

2023-02-16 07:54 UTC, whityha commented on src/command/AddCommand.js
>          const fixed = res !== Infinity ? res.toFixed(3) : Infinity;
результат, который был приведен в нужный нам формат. Она обозначается и сразу же используется.

2023-02-16 07:55 UTC, whityha commented on src/command/command.js
> +    getResult() {
Где мне написать предложения названий методов?

2023-02-16 08:41 UTC, whityha commented on src/command/helpers/result.js
> +            switch (typeof item) {
Он был когда то больше, по этому я его отрефакторил и уже не заменял на условия. Поменял.

2023-02-16 09:17 UTC, anyaprystavka commented on src/command/command.js
> +    getResult() {
здесь в комментарии

2023-02-16 09:18 UTC, anyaprystavka commented on src/command/helpers/result.js
> +            switch (typeof item) {
зачем он нужен? что он делает?

2023-02-16 09:38 UTC, whityha commented on src/command/helpers/result.js
> +            switch (typeof item) {
Мы проходимся по выражению от начала и до конца и проверяем, что у нас в нём. В выражении у нас хранятся и числа, строки(скобки) и команды по очереди. И в свитче, когда это объект, то есть наша команда, то мы выполняем определнные действия как по алгоритму для подсчета через 2 стэка. А если это строка, то есть скобка, то мы выполняем ещё действия, а если это число, то мы просто отправляем его в стек с числами.

2023-02-16 09:50 UTC, whityha commented on src/command/command.js
> +    getResult() {
1. appendCommand - добавляет команду в поле this.expression, a так же выполняет различные действия, как очистка текущего значения, так как если мы нажали * или +, то должны начать вводить новое текущее значение.
2. getResult - получает результат всего выражения, которое находится в поле expression.
3.  equal - метод, который вызывается у калькулятора, когда мы нажимаем =. Кроме получения результата, у нас происходит обновление данных внутри калькулятора, такие как очистка истории, очистка текущего значения, а так же обновление флагов, которые вносят ограничения.
4. changeCurrentValue - метод, который изменяет текущее значение в зависимости от того, на какую клавишу нажали.
5. chageSign - меняем знак у текущего значения (которое вводим) на противоположенный.
6. getLastHistoryItem - получаем последний элемент в истории выражения (та, что отображается вверху над вводом)
7. addItemInExpression - добавляем элемент в конец выражения.
8.  addItemInHistory - добавляем элемент в конец истории.
9. getHistoryDisplay - возвращает историю, которую мы отображаем на дисплее вверху.
10. checkLastHistoryItem - проверяем последнее число, которое стоит у нас в истории. Если там стоит . или -. , то заменяет на 0. Для того, чтобы когда мы ввели . или -. и нажали умножить (*) или любое другое действие, в истории отображался 0, а не . или -.
11. clearCalculator - очищается весь калькулятор и флаги в нём.
12, 13, 14. clearCurrentValue, clearExpression, clearHistory - очищают соответствующие значения.

2023-02-16 10:50 UTC, merged