refactor: change history style. add font Montserrat.
whityha/calculator pull request #9
Opened 2023-02-12 13:16 UTC by whityha

Сделал прокрутку, если история большая, а так же закрепил Title History.

2023-02-12 20:12 UTC, anyaprystavka requested changes

2023-02-12 20:12 UTC, anyaprystavka commented on public/index.html
> +    <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">
Шрифт лучше в globalStyles подключить

2023-02-12 20:12 UTC, anyaprystavka commented on src/components/History/HistoryCC.jsx
>                          <ListItem key={id}>{formula}</ListItem>
formulas?
![image](https://user-images.githubusercontent.com/119484939/218334605-e577da8b-a99b-4894-991e-e98a71355164.png)

2023-02-12 20:22 UTC, whityha commented on src/components/History/HistoryCC.jsx
>                          <ListItem key={id}>{formula}</ListItem>
Я это уже изменил, когда менял логику подсчёта. Это исправленно в другом PR.

2023-02-12 20:23 UTC, whityha commented on public/index.html
> +    <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">
Я подключил, но мне реакт предложил так подключить, по этому перенёс. Сейчас перенесу в global

2023-02-13 07:51 UTC, anyaprystavka requested changes

2023-02-13 07:51 UTC, anyaprystavka commented on src/components/Header/Switcher/styled.js
>      width: 50px;
width/ height / border-radius  в тему

2023-02-13 07:51 UTC, anyaprystavka commented on src/components/History/HistoryFC.jsx
>      const formulas = useSelector(({ display: { formulas: forms } }) => forms);
селекторы для удобства тоже можно вынести в отдельную папку stor'a и потом использовать в тех компонентах, где это нужно

2023-02-13 07:51 UTC, anyaprystavka commented on src/styled/theme.js
> +const settings = {
тему делаем общую для всех компонентов, а не для каждого отдельно
удобно писать объект для стилей потом экспортить его.
![image](https://user-images.githubusercontent.com/119484939/218399426-4ab746d8-7c9d-47a0-baa0-1392ffe00c77.png)
![image](https://user-images.githubusercontent.com/119484939/218399513-a3b4cf99-46ed-4708-b1de-53fcc305c74e.png)

font-weight: ${({ theme }) => theme.fontWeight[800]};

2023-02-13 08:18 UTC, whityha commented on src/components/Header/Switcher/styled.js
>      width: 50px;
Конкретно этот компонент будет удалён. Остальные пересмотрел

2023-02-13 14:00 UTC, anyaprystavka requested changes
theme review for styles

2023-02-13 14:00 UTC, anyaprystavka commented on src/styled/themes/darkTheme.js
> +    max: '100%',
тут хорошо, только структурировать нужно

2023-02-13 14:00 UTC, anyaprystavka commented on src/styled/themes/darkTheme.js
> +    p1: '10px',
только не пиши px, только значения 20, 30, 30
везде

2023-02-13 14:00 UTC, anyaprystavka commented on src/pages/Home/styled.js
> +        grid-template-columns: ${md} ${sm};
часто так пишут 
font-weight: ${({ theme }) => theme.fontWeight[700]};

но тут у тебя читаемо

2023-02-13 14:05 UTC, whityha commented on src/styled/themes/darkTheme.js
> +    max: '100%',
Ок

2023-02-13 14:22 UTC, whityha commented on src/styled/themes/darkTheme.js
> +    p1: '10px',
Сделал

2023-02-13 14:23 UTC, whityha commented on src/styled/themes/darkTheme.js
> +    sm: '30px',
Разделил

2023-02-13 14:26 UTC, whityha commented on src/pages/Home/styled.js
> +        grid-template-columns: ${md} ${sm};
Я специально так оставил. Это более читаемо, чем то, как получилось бы

2023-02-13 17:02 UTC, anyaprystavka commented on src/components/Header/Header/styled.js
> +        text-shadow: 0px 0px 10px ${colorPrimary};
shadow можно отдельно прям вынести

пример с фигмы - shadow
![image](https://user-images.githubusercontent.com/119484939/218523302-cdae2b23-147f-4109-8c80-e848f79c0979.png)

2023-02-13 17:04 UTC, anyaprystavka commented on src/components/History/styled.js
> +        padding: ${`${p0}px ${p2}px ${p5}px ${p2}px`};
тут можно три значения использовать для Padding

2023-02-13 17:06 UTC, anyaprystavka commented on src/styled/theme/options.js
> +export {
я скидывала пример, но старайся использовать импорты по дефолту

2023-02-13 17:13 UTC, anyaprystavka commented on src/components/App.jsx
>      const variant = useSelector(({ control }) => control.theme);
ниже в Suspense должен быть fallback

2023-02-13 17:17 UTC, whityha commented on src/components/History/styled.js
> +        padding: ${`${p0}px ${p2}px ${p5}px ${p2}px`};
done

2023-02-13 17:17 UTC, whityha commented on src/styled/theme/options.js
> +export {
Окей. Но тут константы, по этому так.

2023-02-13 17:20 UTC, whityha commented on src/components/Header/Header/styled.js
> +        text-shadow: 0px 0px 10px ${colorPrimary};
сделал.

2023-02-13 17:22 UTC, whityha commented on src/components/App.jsx
>      const variant = useSelector(({ control }) => control.theme);
сделал

2023-02-13 17:33 UTC, anyaprystavka requested changes

2023-02-13 17:33 UTC, anyaprystavka commented on src/components/App.jsx
> +            <Suspense fallback="Loading...">
лучше добавить spinner,  а не текст

2023-02-13 17:33 UTC, anyaprystavka commented on src/styled/theme/theme.js
> +        textShadow: `0px 0px 10px ${COLORS.white}`,
он должен быть добавлен в options отдельным объектом

2023-02-13 18:16 UTC, whityha commented on src/styled/theme/theme.js
> +        textShadow: `0px 0px 10px ${COLORS.white}`,
Добавил.

2023-02-13 18:16 UTC, whityha commented on src/components/App.jsx
> +            <Suspense fallback="Loading...">
добавил

2023-02-14 06:05 UTC, anyaprystavka approved these changes

2023-02-14 06:32 UTC, merged